name: "Podcast Generator"
author: "Kotham"
description: "Genrators like content"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: Commiters mail id
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: Commiters name
    required: true
    default: ${{ github.actor }}